export default Object.freeze({
    id: 2,
    codigoIdioma: 'en',
    nombre: 'English',
    nombreNativo: 'English',
    tags: Object.freeze({
        1: 'Profile',
        2: 'Name',
        3: 'Email',
        4: 'Country',
        5: 'Language',
        6: 'Profile photo',
        7: 'Change photo',
        8: 'Save',
        9: 'Cancel',
        10: 'Loading profile...',
        11: 'Could not load the profile',
        12: 'Loading...',
        13: 'Something went wrong',
        14: 'Retry',
        15: 'Close',
        16: 'Search',
        17: 'No results',
        18: 'Log in',
        19: 'Sign up',
        20: 'Email',
        21: 'Password',
        22: 'Continue',
        23: 'Select language',
        24: 'Language saved',
        25: 'Image type not allowed',
        26: 'The image cannot exceed 5 MB',
        27: 'Photo unavailable',
        28: 'Countries',
        29: 'Select country',
        30: 'Loading countries...',
        31: 'Back',
        32: 'Next',
    }),
});
