export default Object.freeze({
    id: 1,
    codigoIdioma: 'es',
    nombre: 'Español',
    nombreNativo: 'Español',
    tags: Object.freeze({
        1: 'Perfil',
        2: 'Nombre',
        3: 'Correo electrónico',
        4: 'País',
        5: 'Idioma',
        6: 'Foto de perfil',
        7: 'Cambiar foto',
        8: 'Guardar',
        9: 'Cancelar',
        10: 'Cargando perfil...',
        11: 'No se pudo cargar el perfil',
        12: 'Cargando...',
        13: 'Ocurrió un error',
        14: 'Reintentar',
        15: 'Cerrar',
        16: 'Buscar',
        17: 'Sin resultados',
        18: 'Iniciar sesión',
        19: 'Registrarse',
        20: 'Correo electrónico',
        21: 'Contraseña',
        22: 'Continuar',
        23: 'Seleccionar idioma',
        24: 'Idioma guardado',
        25: 'Tipo de imagen no permitido',
        26: 'La imagen no puede superar 5 MB',
        27: 'Foto no disponible',
        28: 'Países',
        29: 'Seleccionar país',
        30: 'Cargando países...',
        31: 'Volver',
        32: 'Siguiente',
    }),
});
