export default Object.freeze({
    id: 3,
    codigoIdioma: 'fr',
    nombre: 'Français',
    nombreNativo: 'Français',
    tags: Object.freeze({
        1: 'Profil',
        2: 'Nom',
        3: 'E-mail',
        4: 'Pays',
        5: 'Langue',
        6: 'Photo de profil',
        7: 'Changer la photo',
        8: 'Enregistrer',
        9: 'Annuler',
        10: 'Chargement du profil...',
        11: 'Impossible de charger le profil',
        12: 'Chargement...',
        13: "Une erreur s'est produite",
        14: 'Réessayer',
        15: 'Fermer',
        16: 'Rechercher',
        17: 'Aucun résultat',
        18: 'Se connecter',
        19: "S'inscrire",
        20: 'E-mail',
        21: 'Mot de passe',
        22: 'Continuer',
        23: 'Sélectionner la langue',
        24: 'Langue enregistrée',
        25: "Type d'image non autorisé",
        26: "L'image ne peut pas dépasser 5 Mo",
        27: 'Photo indisponible',
        28: 'Pays',
        29: 'Sélectionner un pays',
        30: 'Chargement des pays...',
        31: 'Retour',
        32: 'Suivant',
    }),
});
