export default Object.freeze({
    id: 4,
    codigoIdioma: 'it',
    nombre: 'Italiano',
    nombreNativo: 'Italiano',
    tags: Object.freeze({
        1: 'Profilo',
        2: 'Nome',
        3: 'E-mail',
        4: 'Paese',
        5: 'Lingua',
        6: 'Foto del profilo',
        7: 'Cambia foto',
        8: 'Salva',
        9: 'Annulla',
        10: 'Caricamento del profilo...',
        11: 'Impossibile caricare il profilo',
        12: 'Caricamento...',
        13: 'Si è verificato un errore',
        14: 'Riprova',
        15: 'Chiudi',
        16: 'Cerca',
        17: 'Nessun risultato',
        18: 'Accedi',
        19: 'Registrati',
        20: 'E-mail',
        21: 'Password',
        22: 'Continua',
        23: 'Seleziona lingua',
        24: 'Lingua salvata',
        25: 'Tipo di immagine non consentito',
        26: "L'immagine non può superare 5 MB",
        27: 'Foto non disponibile',
        28: 'Paesi',
        29: 'Seleziona paese',
        30: 'Caricamento dei paesi...',
        31: 'Indietro',
        32: 'Avanti',
    }),
});
