export default Object.freeze({
    id: 5,
    codigoIdioma: 'pt',
    nombre: 'Português',
    nombreNativo: 'Português',
    tags: Object.freeze({
        1: 'Perfil',
        2: 'Nome',
        3: 'E-mail',
        4: 'País',
        5: 'Idioma',
        6: 'Foto de perfil',
        7: 'Alterar foto',
        8: 'Salvar',
        9: 'Cancelar',
        10: 'Carregando perfil...',
        11: 'Não foi possível carregar o perfil',
        12: 'Carregando...',
        13: 'Ocorreu um erro',
        14: 'Tentar novamente',
        15: 'Fechar',
        16: 'Pesquisar',
        17: 'Nenhum resultado',
        18: 'Entrar',
        19: 'Cadastrar-se',
        20: 'E-mail',
        21: 'Senha',
        22: 'Continuar',
        23: 'Selecionar idioma',
        24: 'Idioma salvo',
        25: 'Tipo de imagem não permitido',
        26: 'A imagem não pode exceder 5 MB',
        27: 'Foto indisponível',
        28: 'Países',
        29: 'Selecionar país',
        30: 'Carregando países...',
        31: 'Voltar',
        32: 'Próximo',
    }),
});
